# Name: Dion Toh Siyong
# Matric No: U2021674D

## CZ1104 Lab 3

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import string
import pandas as pd

# Question 1

### Reducing 5x5 GF(2) matrix

In [2]:
rowlist = np.array([[0,0,1,0,1],
                    [0,0,0,1,0],
                    [1,0,1,0,1],
                    [0,0,0,0,1],
                    [0,0,0,1,0]]) #GF(2)

print("\nOriginal:\n", rowlist, '\n')

new_rowlist = []
rows_left = set(range(len(rowlist)))

col_label_list = list(range(0, 5))

for c in col_label_list:
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    print("Rows with nonzero:", rows_with_nonzero)
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        
new_rowlist = np.array(new_rowlist)

print("\nAfter Reduction:\n", new_rowlist)


Original:
 [[0 0 1 0 1]
 [0 0 0 1 0]
 [1 0 1 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]] 

Rows with nonzero: [2]
Rows with nonzero: []
Rows with nonzero: [0]
Rows with nonzero: [1, 4]
Rows with nonzero: [3]

After Reduction:
 [[1 0 1 0 1]
 [0 0 1 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Updated code for reducing 5x5 GF(2) matrix 

In [3]:
rowlist = np.array([[0,0,1,0,1],
                    [0,0,0,1,0],
                    [1,0,1,0,1],
                    [0,0,0,0,1],
                    [0,0,0,1,0]]) #GF(2)

print("\nOriginal:\n", rowlist, '\n')

new_rowlist = []
rows_left = set(range(len(rowlist)))

col_label_list = list(range(0, 5))

for c in col_label_list:
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    print("Rows with nonzero:", rows_with_nonzero)
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        for r in rows_with_nonzero[1:]:
            multiplier = rowlist[r][c]/rowlist[pivot][c]
            for x in range(c,4):
                rowlist[r][x] -= multiplier * rowlist[pivot][x]

new_rowlist = np.array(new_rowlist)

print("\nAfter Reduction:\n", new_rowlist)


Original:
 [[0 0 1 0 1]
 [0 0 0 1 0]
 [1 0 1 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]] 

Rows with nonzero: [2]
Rows with nonzero: []
Rows with nonzero: [0]
Rows with nonzero: [1, 4]
Rows with nonzero: [3]

After Reduction:
 [[1 0 1 0 1]
 [0 0 1 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Question 2

### Reducing 4x4 GF(2) matrix using Gaussian Elimination

In [4]:
rowlist = np.array([[0,0,1,1],
                    [1,0,1,1],
                    [1,0,0,1],
                    [1,1,1,1]]) #GF(2)

print("\nOriginal:\n", rowlist, '\n')

new_rowlist = []
rows_left = set(range(len(rowlist)))

col_label_list = list(range(0, 4))

for c in range(len(rowlist)):
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    print("Rows with nonzero:", rows_with_nonzero)
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        for r in rows_with_nonzero[1:]:
            for x in range(c,4):
                rowlist[r][x] += rowlist[pivot][x]
                rowlist[r][x] %= 2
                
new_rowlist = np.array(new_rowlist)

print("\nAfter Reduction:\n", new_rowlist)


Original:
 [[0 0 1 1]
 [1 0 1 1]
 [1 0 0 1]
 [1 1 1 1]] 

Rows with nonzero: [1, 2, 3]
Rows with nonzero: [3]
Rows with nonzero: [0, 2]
Rows with nonzero: [2]

After Reduction:
 [[1 0 1 1]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 0 1]]


### Reducing 4x4 matrix with general numers using Gaussian Elimination

In [5]:
rowlist = np.array([[4,3,2,1],
                    [3,5,1,9],
                    [4,7,1,3],
                    [9,7,8,1]])

print("\nOriginal:\n", rowlist, '\n')

new_rowlist = []
rows_left = set(range(len(rowlist)))

col_label_list = list(range(0, 4))

for c in range(len(rowlist)):
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    print("Rows with nonzero:", rows_with_nonzero)
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        for r in rows_with_nonzero[1:]:
            multiplier = rowlist[r][c]/rowlist[pivot][c]
            for x in range(c,4):
                rowlist[r][x] -= multiplier * rowlist[pivot][x]
                
new_rowlist = np.array(new_rowlist)

print("\nAfter Reduction:\n", new_rowlist)


Original:
 [[4 3 2 1]
 [3 5 1 9]
 [4 7 1 3]
 [9 7 8 1]] 

Rows with nonzero: [0, 1, 2, 3]
Rows with nonzero: [1, 2]
Rows with nonzero: [2, 3]
Rows with nonzero: [3]

After Reduction:
 [[  4   3   2   1]
 [  0   2   0   8]
 [  0   0  -1 -14]
 [  0   0   0 -43]]
